export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCESS = "REGISTER_USER_SUCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";

export const VERIFY_USER_REQUEST = "VERIFY_USER_REQUEST";
export const VERIFY_USER_SUCESS = "VERIFY_USER_SUCESS";
export const VERIFY_USER_ERROR = "VERIFY_USER_ERROR";

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCESS = "LOGIN_USER_SUCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";



export const USER_AUTH_SUCESS = "USER_AUTH_SUCESS";
export const USER_AUTH_FAILURE = "USER_SUCESS_FAILURE";


export const LOGOUT_USER_REQUEST = "LOGOUT_USER_REQUEST";
export const LOGOUT_USER_SUCESS = "LOGOUT_USER_SUCESS";
export const LOGOUT_USER_FAILURE =  "LOGOUT_USER_FAILURE";


export const EMPTY_USER_SUCESS_MESSAGE = "EMPTY_USER_SUCESS_MESSAGE";
export const EMPTY_USER_FAILURE_MESSAGE = "EMPTY_USER_FAILURE_MESSAGE";
